name: gad_ai
description: A smart AI assistant app for translation, OCR, charts, games, and education.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # UI & State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.5
  go_router: ^12.1.1

  # Image & Camera
  camera: ^0.10.5+2
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0

  # AI & OCR
  google_mlkit_text_recognition: ^0.11.0
  tflite_flutter: ^0.10.2
  http: ^1.2.1

  # Firebase (Optional)
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0

  # UI Enhancements
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # Dark mode & Theme
  dynamic_color: ^1.6.6
  flex_color_scheme: ^7.3.1

  # Crypto/Payment
  web3dart: ^2.6.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/gad_ai_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/gad_ai_icon.png
  android: true
  ios: true
  web: false
